### PR TITLE
chore(eredis): avoid collisions between packages using context

### PR DESCRIPTION
**Pull request by zcong1993**
fix https://staticcheck.io/docs/checks#SA1029

### CODE REVIEW

**Comment by askuy** [comment]
please fix like this: https://github.com/gotomicro/ego/blob/34fbc797c77cbdfe6d6b057af80c3de45cfec291/client/ehttp/interceptor.go#L79

https://stackoverflow.com/questions/40891345/fix-should-not-use-basic-type-string-as-key-in-context-withvalue-golint
https://blog.golang.org/context#TOC_3.2.
https://golang.org/pkg/context/#WithValue

**Comment by zcong1993** [comment]
> thanks for your pr. we can do it better, please fix like this: https://github.com/gotomicro/ego/blob/34fbc797c77cbdfe6d6b057af80c3de45cfec291/client/ehttp/interceptor.go#L79
> 
> https://stackoverflow.com/questions/40891345/fix-should-not-use-basic-type-string-as-key-in-context-withvalue-golint https://blog.golang.org/context#TOC_3.2. https://golang.org/pkg/context/#WithValue

done

**Comment by askuy** [comment]
> > thanks for your pr. we can do it better, please fix like this: https://github.com/gotomicro/ego/blob/34fbc797c77cbdfe6d6b057af80c3de45cfec291/client/ehttp/interceptor.go#L79
> > https://stackoverflow.com/questions/40891345/fix-should-not-use-basic-type-string-as-key-in-context-withvalue-golint https://blog.golang.org/context#TOC_3.2. https://golang.org/pkg/context/#WithValue
> 
> done

Use type struct{} much better.

type ctxKey struct{} // or exported to use outside the package

ctx = context.WithValue(ctx, ctxKey{}, 123)
fmt.Println(ctx.Value(ctxKey{}).(int) == 123) // true
Reference: https://golang.org/pkg/context/#WithValue

The provided key must be comparable and should not be of type string or any other built-in type to avoid collisions between packages using context. Users of WithValue should define their own types for keys. To avoid allocating when assigning to an interface{}, context keys often have concrete type struct{}. Alternatively, exported context key variables' static type should be a pointer or interface.

**Comment by zcong1993** [comment]
> > > thanks for your pr. we can do it better, please fix like this: https://github.com/gotomicro/ego/blob/34fbc797c77cbdfe6d6b057af80c3de45cfec291/client/ehttp/interceptor.go#L79
> > > https://stackoverflow.com/questions/40891345/fix-should-not-use-basic-type-string-as-key-in-context-withvalue-golint https://blog.golang.org/context#TOC_3.2. https://golang.org/pkg/context/#WithValue
> > 
> > 
> > done
> 
> Use type struct{} much better.
> 
> type ctxKey struct{} // or exported to use outside the package
> 
> ctx = context.WithValue(ctx, ctxKey{}, 123) fmt.Println(ctx.Value(ctxKey{}).(int) == 123) // true Reference: https://golang.org/pkg/context/#WithValue
> 
> The provided key must be comparable and should not be of type string or any other built-in type to avoid collisions between packages using context. Users of WithValue should define their own types for keys. To avoid allocating when assigning to an interface{}, context keys often have concrete type struct{}. Alternatively, exported context key variables' static type should be a pointer or interface.

already use type struct{}

**Pull request merged**
